name: TestWorkflow

on: workflow_dispatch

jobs:
  GenerateConfig:
    runs-on: ubuntu-latest
    outputs:
      commit_exit_code: ${{ steps.final.outputs.commit_exit_code }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create Release Branch
      run: |
        date=$(date '+%Y%m%d')
        git checkout -b release-${date}
    - name: Configure Bot Alias
      run: |
        git config --global user.name "GenerateConfig Action"
        git config --global user.email "gcaction@github.com"
    - name: Do something
      run: |
        touch testFile.txt
        git add .
    - name: Commit and Push Changes
      id: final
      run: |
        set +e
        git commit -m "Release Kickoff"
        echo "commit_exit_code=$?" >> "$GITHUB_OUTPUT"
        git status
        date=$(date '+%Y%m%d')
        git push --set-upstream origin release-${date}
        set -e
    - name: Open PR for Branch 
      if: ${{ steps.final.outputs.commit_exit_code == 0 }}
      run: |
        date=$(date '+%Y%m%d')
        gh pr create --base main --head release-${date} --title "Release ${date}" --body "test blahblah"
  PushToCodeCommit:
    needs: GenerateConfig
    if: ${{ needs.GenerateConfig.outputs.commit_exit_code == 0 }}
    runs-on: ubuntu-latest
    env: 
      GH_TOKEN: ${{ secrets.TEST_PAT }}
    permissions:
      id-token: write
      contents: write
    steps:
    - name: Configure prereqs
      run: |
        git config --global user.name "Github Action"
        git config --global user.email "action@github.com"
    - name: Mirror to shinkansen branch on codecommit repository
      run: | 
        date=$(date '+%Y%m%d')
        git clone https://github.com/hozkaya2000/amazon-ecs-ami ecsAmiGithub
        cd ecsAmiGithub
        git checkout release-${date}
        git push origin release-${date}:fakeShinkansen
